stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project ExtensionKit/ExtensionKit.xcodeproj -scheme ExtensionKit | xcpretty
    - xcodebuild test -project ExtensionKit/ExtensionKit.xcodeproj -scheme ExtensionKit -destination 'platform=iOS Simulator,name=iPhone 5s' | xcpretty -s
  tags:
    - MacBookPro
