disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - conditional_returns_on_newline
  - no_extension_access_modifier
  - number_separator
  - syntactic_sugar
  - explicit_type_interface

opt_in_rules: # some rules are only opt-in
  - empty_count
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - explicit_init
  - explicit_type_interface
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline


line_length:
  warning: 200
  error: 250
